on:
  push:
    branches: [ dev ]
jobs:
  test-zenodo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test zenodo
        run: |
          curl https://zenodo.org/record/6428433/files/sandialabs/ufjc-v1.3.0.zip?download=1 -o ufjc.zip
          unzip -d ufjc/ ufjc.zip
          mv ufjc/*/* ufjc/
          cd ufjc/
          python setup.py install
          cd ../../
          python -m ufjc.tests
