on:
  push:
    branches: [ dev ]
jobs:
  test-zenodo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test zenodo
        run: |
          curl https://zenodo.org/record/6428433/files/sandialabs/ufjc-v1.3.0.zip?download=1 -o clone.zip
          unzip -d clone/ clone.zip
          cd clone/$(ls clone/)
          pip install numpy scipy
          python -m ufjc.tests
